# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schame
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  # redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: ""
    timeout: 1000
    block-when-exhausted: false
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  session:
    store-type: none

  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 123456@qq.com #发送邮件的邮箱地址
    password:  * #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 123456@qq.com # 发送邮件的地址，和上面username一致可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
shiro:
  loginUrl: /login.html
  unauthorizedUrl: /unauthorized
  sessionManager:
    sessionIdUrlRewritingEnabled: false