# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schame
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  # redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: ""
    timeout: 1000
  session:
    store-type: none
shiro:
  loginUrl: /login.html
  unauthorizedUrl: /unauthorized
  sessionManager:
    sessionIdUrlRewritingEnabled: false